export const projects = [{
    id: 0,
    title: 'Budget Buddy',
    description: 'A monthly budget tracker to help you keep track of your spending',
    technologies: ['React', 'TypeScript', 'Flask', 'Python', 'HTML', 'CSS'],
    liveLink: 'https://yourbudgetbuddy.vercel.app/',
    githubLink: 'https://github.com/MrSnoodle01/Budget-Management',
    image: '/appImages/BudgetBuddy.png',
}, {
    id: 1,
    title: 'Grav Lab',
    description: 'A 2D game developed in Unity where players solve puzzles using gravity manipulation mechanics',
    technologies: ['C#', 'Unity'],
    liveLink: 'https://mrsnoodle.itch.io/grav-lab',
    githubLink: 'https://github.com/MrSnoodle01/Unity-Gravity-Game',
    image: '/appImages/GravLab.png',
}, {
    id: 2,
    title: 'Algorithm Visualizer',
    description: 'A web application that visualizes various algorithms in action, helping users understand how they work',
    technologies: ['JavaScript', 'HTML', 'CSS'],
    liveLink: 'https://mrsnoodle01.github.io/Algorithms/',
    githubLink: 'https://github.com/MrSnoodle01/Algorithms',
    image: '/appImages/AlgorithmProject.png',
}, {
    id: 3,
    title: 'Guess the Number of Beans',
    description: 'A daily game where users have 5 tries to guess the number of jelly beans in a container',
    technologies: ['React', 'TypeScript', 'HTML', 'CSS'],
    liveLink: 'https://mrsnoodle01.github.io/Count-the-beans/',
    githubLink: 'https://github.com/MrSnoodle01/Count-the-beans',
    image: '/appImages/BeanGame.png',
}, {
    id: 4,
    title: 'Termination',
    description: 'A retro arcade game made in 48 hours for a local hackathon',
    technologies: ['C#', 'Unity'],
    liveLink: 'https://mrsnoodle.itch.io/termination',
    githubLink: 'https://github.com/MrSnoodle01/Vegas-Hackathon-2025',
    image: '/appImages/Termination.png',
}, {
    id: 5,
    title: 'MTG Draft Tracker',
    description: 'A website created to keep track of Magic The Gathering games I play with my friends',
    technologies: ['React', 'TypeScript', 'HTML', 'CSS'],
    liveLink: 'https://mtg-draft-history.vercel.app/',
    githubLink: 'https://github.com/MrSnoodle01/mtg-draft-history',
    image: '/appImages/MtgDraftHistory.png',
}]