export const projects = [{
    id: 0,
    title: 'Budget Buddy',
    description: 'A monthly budget tracker to help you keep track of your spending',
    technologies: ['React', 'TypeScript', 'Flask', 'Python', 'HTML', 'CSS'],
    link: 'https://yourbudgetbuddy.vercel.app/',
    image: '/appImages/BudgetBuddy.png',
}, {
    id: 1,
    title: 'Grav Lab',
    description: 'A 2D game developed in Unity where players solve puzzles using gravity manipulation mechanics',
    technologies: ['C#', 'Unity'],
    link: 'https://mrsnoodle.itch.io/grav-lab',
    image: '/appImages/GravLab.png',
}, {
    id: 2,
    title: 'Algorithm Visualizer',
    description: 'A web application that visualizes various algorithms in action, helping users understand how they work',
    technologies: ['JavaScript', 'HTML', 'CSS'],
    link: 'https://mrsnoodle01.github.io/Algorithms/',
    image: '/appImages/AlgorithmProject.png',
}, {
    id: 3,
    title: 'Guess the Number of Beans',
    description: 'A daily game where users have 5 tries to guess the number of jelly beans in a container',
    technologies: ['React', 'TypeScript', 'HTML', 'CSS'],
    link: 'https://mrsnoodle01.github.io/Count-the-beans/',
    image: '/appImages/BeanGame.png',
}, {
    id: 4,
    title: 'Termination',
    description: 'A retro arcade game made in 48 hours for a local hackathon',
    technologies: ['C#', 'Unity'],
    link: 'https://mrsnoodle.itch.io/termination',
    image: '/appImages/Termination.png',
}, {
    id: 5,
    title: 'Portfolio Website',
    description: 'A personal portfolio website showcasing my projects and skills, built with React',
    technologies: ['React', 'TypeScript', 'HTML', 'CSS'],
    link: 'https://mrsnoodle01.github.io',
    image: '/appImages/PersonalSite.png',
}]